### PR TITLE
Better URI handling; fixes #571

### LINKED ISSUE #571: Web context lost when WebServices are deployed in an specific context
Dear colleagues,

The Plato Science Operations Centre at ESAC is trying to setup a CDP4 backend using the Webservices and Database Docker distributions.  This service is intended to support the Mission Parameter DB.

We've successfully installed and deployed the two Docker images in a local server inside our network.  In order to make the service available from the outside world, we have registered a public server in our DMZ in our ESA firewall with the following redirection:

<public.server.IP>/mdb redirects to <local.server.IP>:5000

From the web, it works.  We can access to <public.server.IP>/mdb/SiteDirectory and we get a response from the CDP4 Webservices.

From the CDP4 UI, it does not work.  We get a '503: Service Temporarily Unavailable' because the backend is redirecting to <public.server.IP>/app (the context /mdb is lost).

We think the CDP4 UI is assuming that the service is deployed directly in port 5000 and it's overwriting the web context redirecting to /app instead of to /mdb/app.  

Could you please analyse this issue?

We appreciate your time and help.

Best regards...

--

Antonio

### PR DESCRIPTION
**Pull request by alexatrhea**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Improved consistency in trailing / before credentials class is instantiated.
Updated with SDK 6.3.0

### CODE REVIEW

File: CDP4ShellDialogs/ViewModels/DataSourceSelectionViewModel.cs [hunk 1]
```diff
@@ -392,6 +392,14 @@ public ReactiveList<UriRowViewModel> AvailableUris
         /// </returns>
         private async Task ExecuteOk()
```
Comment (alexatrhea) [inline CDP4ShellDialogs/ViewModels/DataSourceSelectionViewModel.cs:393]: The only relevant code changes outside of the SDK update.

**Review by samatrhea — APPROVED** [review]
looks good to me, can you check that in the other tools such as DEHP related and SAT this is followed. Perhaps also update one of the wiki pages to make that explicit?

**Review by lxatrhea — APPROVED** [review]
