### PR TITLE
ReqIF export with SimpleParameterValues closes #237.

### LINKED ISSUE #237: export to reqif fails
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When trying to export the requirements from a model to a ReqIF file, the export fails. The requirements set in question contains:
  - Requirements Specification
  - Requirement Groups
  - Requirements
  - SimpleParameterValues

### Steps to Reproduce
Open a model that contains requirements and notice that it fails.

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 4.0.4

### PR DESCRIPTION
**Pull request by alexatrhea**
Hotfix to allow the export. Needs to be iterated to define the proper flow.

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [ ] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### CODE REVIEW

File: Requirements/ReqIFDal/ReqIFBuilder.cs [hunk 1]
```diff
@@ -300,15 +300,10 @@ private void InstantiateRequirementType()
             var requirements = this.exportedIteration.RequirementsSpecification.SelectMany(s => s.Requirement);
             foreach (var requirement in requirements)
             {
+                // TODO: short term fix. The intent of reuse of spec type with use of applied rules is a bit unintuitive and convoluted without clear reasoning. Needs to be completely looked over.
```
Comment (samatrhea) [inline Requirements/ReqIFDal/ReqIFBuilder.cs]: please add a GH issue for this and put the url of it in the code so we do not forget. a TODO will be forgotten.
