### PR TITLE
Fixes #107 ShortName of SimpleParameterValue now shown in the grid in the first column. Fixed bug with creating a SimpleParameterValue in a new Requirement.

### LINKED ISSUE #107: Add the shortname of the parametertype to the list of SimpleParameterValues on the Requirements Dialog
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The Requirements dialog shows the list of SimpleParameterValues. This list should show in the first column the shortname of the referenced ParameterType.

### Steps to Reproduce
NA

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 2.1.0

### PR DESCRIPTION
**Pull request by alexatrhea**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Both the RequirementsDialog and the SimpleParameterValueDialog now have the ParameterType Shortname displayed in the lists.

Also fixes a bug in the tooltip services that would cause an exception and thus prevent creating SimpleParameterValues while creating the Requirement itself. The call to derived `.Owner` property in the service would throw a `ContainmentException` because, of course, the container chain has not been entirely set for the things. For now the fix is catch all as there are suspected possible other random cases where this can happen. @samatrhea please chime in if a more thorough case by case fix is wanted.

### CODE REVIEW

File: CDP4Composition/Services/TooltipService.cs [hunk 1]
```diff
@@ -32,6 +32,13 @@ public static class TooltipService
         /// <returns></returns>
         public static string Tooltip(this Thing thing)
         {
+            if (thing.ChangeKind == ChangeKind.Create)
```
Comment (samatrhea) [inline CDP4Composition/Services/TooltipService.cs]: makes sense to me!
