### PR TITLE
The style of the header of the Product Tree is not alligned with the rest of the panels; fixes #328

### LINKED ISSUE #328: The style of the header of the Product Tree is not alligned with the rest of the panels
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The headers of the different panels show the name of the person, data-source, model name etc. The panels `all`  have the same style (bold for the property name, left outlined). The product tree panel does not follow this style

image

- [ ] If the Option dependent header is not a seperate user control, make it so. (See Other header as example.
- [ ] Align styles and spacing to be identical, or make into a single control that has Option visibility.
- [ ] Check if any other browsers are using this header and if so, refactor.

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 5.1.1

### PR DESCRIPTION
**Pull request by nathanatrhea**
Product tree header updated
BrowserHeader Option field added; fixes #328

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

- [x] If the Option dependent header is not a seperate user control, make it so. (See Other header as example.
- [x] Align styles and spacing to be identical, or make into a single control that has Option visibility.
- [x] Check if any other browsers are using this header and if so, refactor.

### CODE REVIEW

File: ProductTree/ViewModels/ProductTreeViewModel.cs [hunk 1]
```diff
@@ -135,6 +166,16 @@ public ProductTreeViewModel(Option option, ISession session, IThingDialogNavigat
...
         }
 
+        /// <summary>
+        /// Gets the value whether <see cref="ProductTreeViewModel"/> is option dependant
+        /// the value is used by the <see cref="CDP4CommonView.Views.BrowserHeader"/> to display or not the option informations
+        /// </summary>
+        public bool IsOptionDependant
+        {
+            get => this.isOptionDependant;
+            private set => this.RaiseAndSetIfChanged(ref this.isOptionDependant, value);
```
Comment (alexatrhea) [inline ProductTree/ViewModels/ProductTreeViewModel.cs:176]: I dont think this should be private for binding, or the mode has to be explicitly OneWay?.

File: CDP4Composition/Converters/BooleanToVisibilityConverter.cs [hunk 2]
```diff
@@ -1,6 +1,26 @@
 ﻿// --------------------------------------------------------------------------------------------------------------------
 // <copyright file="BooleanToVisibilityConverter.cs" company="RHEA System S.A.">
-//   Copyright (c) 2015 RHEA System S.A.
+//    Copyright (c) 2015-2020 RHEA System S.A.
+//
+//    Author: Sam Gerené, Alex Vorobiev, Merlin Bieze, Naron Phou, Patxi Ozkoidi, Alexander van Delft, Mihail Militaru
```
Comment (samatrhea) [inline CDP4Composition/Converters/BooleanToVisibilityConverter.cs:5]: please remove Mihail

File: ProductTree/ViewModels/ProductTreeViewModel.cs (hunk 1 above)
Comment (samatrhea) [reply ProductTree/ViewModels/ProductTreeViewModel.cs:176]: Not sure what this property is about... the ProductTree is always for a specific Option, so this property is not needed here.
