### PR TITLE
Partly fixes #184: check participant domain on insert and update

### LINKED ISSUE #184: IME: Opening EM for participants without domain assignment leads to internal server error - improve checking mechanism and user feedback
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4 Web Services
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Currently, it's doesn't seem to be possible to assign a participant - e.g. a customer role- to an engineering model without assigning a domain (which shouldn't be required for a customer) and have him successfully opening an engineering model.

This should be possible (e.g. for customer, observers)

The situation is as follows in testing (on public server)
* when creating a participant, it is NOT possible to NOT assign a domain. This gives an error message: 
```


The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:The \u0027Domain\u0027 property of a \u0027Participant\u0027 is mandatory and must have at least one entry."
```

* only when assigning a domain, the person can be added as a participant. Note that the participant is then able to connect to the server and open the engineering model

* it is possible to edit the participant (in another CDP instance with admin user) and remove the domain assignment. This doesn't give an error message

* without this domain assignment, the participant is not able to open the engineering model. Error message:
```
The data-source replied with code InternalServerError: Internal Server Error
```

### Steps to Reproduce

Reproducable with the following steps:
* as admin create test person (with non-admin role, e.g. CD team member) and try to create without domain - error message
* as admin, continue to create test user by assigning domain to test user
* as test user check that the test user can now open the engineering model, and close again
* as admin user, edit participant, removing domain assignment
* as test user, try to open engineering model - error message

### System Configuration

- CDP4 Web Services version:
  - [ ] CDP4Common:  
  - [ ] PostrgreSQL: 
  - [ ] Other:       
- Environment (Operating system, version and so on):
- .NET Framework version:
- Mono version:
- Additional information:

CDP4 IME Log file for test user as participant, with last action trying to open model trying to open model without domain assignment

[CDP4IME - test user as participant.log](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/files/3550724/CDP4IME.-.test.user.as.participant.log)

### PR DESCRIPTION
**Pull request by lxatrhea**
- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)
It should not be possible anymore to save a participant without a minimal of 1 DomainOfExpertise set in the edit- and create participant dialogs.

Other part of the fix for issue [#184](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/184), regarding the user feedback, is solved in Webservice issue [#94](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/94).

### CODE REVIEW

File: CDP4SiteDirectory/ViewModels/Dialogs/ParticipantDialogViewModel.cs [hunk 1]
```diff
@@ -180,7 +196,18 @@ protected override void UpdateOkCanExecute()
...
-            this.SelectedSelectedDomain = this.SelectedSelectedDomain ?? this.Domain.FirstOrDefault();
+            if (this.Domain.All(x => x.Iid != this.SelectedSelectedDomain?.Iid))
+            {
+                this.SelectedSelectedDomain = this.Domain.FirstOrDefault();
+            }
+
+            this.UpdateOkCanExecute();
+        }
+
+        protected override void Dispose(bool disposing)
```
Comment (alexatrhea) [inline CDP4SiteDirectory/ViewModels/Dialogs/ParticipantDialogViewModel.cs]: docs please
