### PR TITLE
Move all Models iteration functionality to ShellDialog ; fixes #204

### LINKED ISSUE #204: Move open model logic to ShellDialogs plugin to remove the dependency on the complete EngineeringModel plugin
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In preparation of making a light weight Excel Addin where users can only connect to a server, the open model views and viewmodels and business logic needs to be moved to the ShellDialogs plugin.

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 4.0.4

### PR DESCRIPTION
**Pull request by mmilitaru**
#204 Move all related tests
#204 change Excel addin ribbon and verification to point to the new project

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
#204 Move open model logic to ShellDialogs plugin to remove the dependency on the complete EngineeringModel plugin

### CODE REVIEW

File: CDP4ShellDialogsTestFixture/HomeRibbonTestFixture.cs [hunk 1]
```diff
@@ -4,7 +4,7 @@
 // </copyright>
 // --------------------------------------------------------------------------------------------------------------------
 
-namespace CDP4EngineeringModel.Tests.RibbonControls
+namespace CDP4ShellDialogs.Tests.RibbonControls
```
Comment (alexatrhea) [inline CDP4ShellDialogsTestFixture/HomeRibbonTestFixture.cs]: It would seem that this file is no longer needed, does not have any tests that I see.

File: EngineeringModel.Tests/app.config [hunk 2]
```diff
@@ -1,5 +1,10 @@
-﻿<?xml version="1.0" encoding="utf-8"?>
+<?xml version="1.0" encoding="utf-8"?>
```
Comment (samatrhea) [inline EngineeringModel.Tests/app.config]: please undo changes

Comment (mmilitaru) [reply EngineeringModel.Tests/app.config]: The file has been saved as encoding with signature.

File: CDP4ShellDialogsTestFixture/HomeRibbonTestFixture.cs (hunk 1 above)
Comment (mmilitaru) [reply CDP4ShellDialogsTestFixture/HomeRibbonTestFixture.cs]: Test case has been removed
