### PR TITLE
Fixes #288 devexpress upgrade

### LINKED ISSUE #288: Upgrade to DevExpress 19.2.5
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Upgrade the complete solution to DevExpress WPF components version 19.2.5

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 5.0.2

### PR DESCRIPTION
**Pull request by lxatrhea**
- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

Upgrade DevExpress controls to version 19.2.5
Fixed failing unit tests

### CODE REVIEW

File: CDP4CommonView/Diagram/Views/Cdp4DiagramConnector.cs [hunk 1]
```diff
@@ -193,7 +193,7 @@ private void Initialize()
             BindingOperations.SetBinding(this, TargetProperty, targetBinding);
 
             var textBinding = ViewUtils.CreateBinding(this.DataContext, "DisplayedText", BindingMode.OneWay);
-            BindingOperations.SetBinding(this, TextProperty, textBinding);
+            BindingOperations.SetBinding(this, ContentProperty, textBinding);
```
Comment (alexatrhea) [inline CDP4CommonView/Diagram/Views/Cdp4DiagramConnector.cs]: Can you verify please that this did not break anything too much in the diagramming?

File: CDP4IMEInstaller/CDP4IME.wxs [hunk 2]
```diff
@@ -44,167 +44,167 @@
       <!-- DevExpress Dependencies -->
 
       <Component Id="_A726CFBE26D5" Guid="{90BBA601-EC72-48D0-B370-A726CFBE26D5}" Win64="$(var.Win64)">
```
Comment (alexatrhea) [inline CDP4IMEInstaller/CDP4IME.wxs]: Under the impression that in devexpress 19.2 the number of required files and some names have changed. This seems incomplete.

File: CDP4RelationshipEditor/Controls/BinaryRelationshipDiagramConnector.cs [hunk 3]
```diff
@@ -49,7 +49,7 @@ private void UpdateProperties()
 
             if (relationship != null)
             {
-                this.Text = string.Join(", ", relationship.AppliedBinaryRelationshipRules.Select(b => b.Name)).PadLeft(1).PadRight(1);
+                this.Content = string.Join(", ", relationship.AppliedBinaryRelationshipRules.Select(b => b.Name)).PadLeft(1).PadRight(1);
```
Comment (alexatrhea) [inline CDP4RelationshipEditor/Controls/BinaryRelationshipDiagramConnector.cs]: Related to the question above?

File: CDP4RelationshipEditor/Controls/MultiRelationshipDiagramConnector.cs [hunk 4]
```diff
@@ -49,7 +49,7 @@ private void UpdateProperties()
             this.BeginItem = this.Source;
             this.EndItem = this.Target;
             
-            this.Text = string.Join(", ", this.GetAppliedMultiRelationshipRules().Select(b => b.Name));
+            this.Content = string.Join(", ", this.GetAppliedMultiRelationshipRules().Select(b => b.Name));
```
Comment (alexatrhea) [inline CDP4RelationshipEditor/Controls/MultiRelationshipDiagramConnector.cs]: Ditto

**Comment by alexatrhea** [comment]
Done with the diagramming refactor for now.
